name: Build ISOPRIME Chatwoot Image

on:
  push:
    branches:
      - isoprime-custom-v4.12.1
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/eulucassantos/chatwoot-isoprime" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: eulucassantos
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/eulucassantos/chatwoot-isoprime:v4.12.1-custom
            ghcr.io/eulucassantos/chatwoot-isoprime:latest